name: meaSuite
main: me.turt2live.meaSuite.plugin.Loader
version: 1.0.5
description: The plugin that does most things
author: Turt2Live
authors: [Turt2Live, Sayshal]
website: http://dev.bukkit.org/server-mods/measuite/
softdepend: [mChatSuite, CommandBook, Factions, mcMMO, Spout]
commands:
  mea:
    description: See and use various functions of meaSuite-Core
    permission: meaSuite.mea

permissions:
    meaSuite.*:
        description: all meaSuite commands
        default: op
        children:
            meaSuite.reload: true
            meaSuite.mea: true
    meaSuite.reload:
        description: reload command
        default: false
    meaSuite.mea:
        description: use the mea command
        default: false